//
// C-vs-TS differential tests: common scenario -> original C and TypeScript -> semantic diff.
//
// Set RECORD_CREF=1 to rewrite test/scenarios/generated/c-reference-random.cases.ts
// from the executed C (npm run cref:record). The recorded file lets the Lua
// runner replay C-verified outcomes without a C compiler.
//

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { get2dRange, getApprox2dRange } from "../../src/core/maths/range";
import { toFloat32 } from "../../src/core/float32";
import { runScenario, type ScenarioOutcome } from "../scenarios/campaign-scenario";
import { C_REFERENCE_RANDOM_CASES } from "../scenarios/generated/c-reference-random.cases";
import { runCRange, runCScenario } from "./c-harness";
import { generateRandomScenarios, mulberry32 } from "./random-scenarios";

const RECORDED_SEED = 20260922;
const RECORDED_COUNT = 250;

function assertNoNegativeZero(value: unknown, path: string): void {
	if (typeof value === "number" && Object.is(value, -0)) {
		throw new Error(`${path} is -0, which the recorded fixture cannot represent`);
	}
	if (typeof value === "object" && value !== null) {
		for (const [k, v] of Object.entries(value)) {
			assertNoNegativeZero(v, `${path}.${k}`);
		}
	}
}

describe("C reference: recorded random scenarios", () => {
	if (process.env.RECORD_CREF === "1") {
		it("records the fixture from the original C", () => {
			const cases = generateRandomScenarios(RECORDED_SEED, RECORDED_COUNT).map((spec, i) => {
				const expected: ScenarioOutcome = runCScenario(spec);
				assertNoNegativeZero(expected, `case ${i}`);
				return { id: `random-${RECORDED_SEED}-${i}`, c: "random scenario, outcome recorded from the original C", spec, expected };
			});
			const text = [
				"//",
				"// GENERATED by `npm run cref:record` from the executed original EECH C",
				`// (c-reference/harness.c, seed ${RECORDED_SEED}). Do not edit.`,
				"//",
				"",
				'import type { ConformanceCase } from "../assess-group-supplies.cases";',
				"",
				`export const C_REFERENCE_RANDOM_CASES: ConformanceCase[] = ${JSON.stringify(cases, null, "\t")};`,
				"",
			].join("\n");
			writeFileSync(join(__dirname, "../scenarios/generated/c-reference-random.cases.ts"), text);
		});
		return;
	}

	it("the fixture is non-trivial", () => {
		expect(C_REFERENCE_RANDOM_CASES.length).toBe(RECORDED_COUNT);
	});

	it("every recorded outcome is still what the original C produces", () => {
		for (const c of C_REFERENCE_RANDOM_CASES) {
			expect(runCScenario(c.spec), c.id).toEqual(c.expected);
		}
	});
});

describe("C reference: live differential", () => {
	it("TypeScript matches the original C on 1500 fresh random scenarios", () => {
		const branches: Record<string, number> = {};
		for (const spec of generateRandomScenarios(0xeec4, 1500)) {
			const c = runCScenario(spec);
			expect(runScenario(spec)).toEqual(c);
			const key = `${spec.op.kind}:${c.result}:${c.transmissions.length}:${c.messages.length}`;
			branches[key] = (branches[key] ?? 0) + 1;
		}
		// the generator must keep reaching the interesting outcomes
		const kinds = Object.keys(branches).join(" ");
		expect(kinds).toContain("assess:ok:4:0");
		expect(kinds).toContain("assess:ok:0:1");
		expect(kinds).toContain("assess:assert:receiver");
		expect(kinds).toContain("assess:assert:keysite");
		expect(kinds).toContain("assess:null-dereference");
		expect(kinds).toContain("closest:ok");
		expect(kinds).toContain("closest:assert:v2");
	});

	it("get_2d_range and get_approx_2d_range match the original C bit for bit", () => {
		const rnd = mulberry32(42);
		for (let i = 0; i < 400; i++) {
			const v = [0, 0, 0, 0].map(() => (rnd() - 0.5) * 10 ** Math.floor(rnd() * 7));
			const c = runCRange(v[0], v[1], v[2], v[3]);
			const a = { x: toFloat32(v[0]), y: 0, z: toFloat32(v[1]) };
			const b = { x: toFloat32(v[2]), y: 0, z: toFloat32(v[3]) };
			expect(get2dRange(a, b)).toBe(c.range);
			expect(getApprox2dRange(a, b)).toBe(c.approx);
		}
	});
});
