//
// C-vs-TS differential tests: common scenario -> original C and TypeScript -> semantic diff.
//
// Set RECORD_CREF=1 to rewrite test/scenarios/generated/c-reference-random.cases.ts
// from the executed C (npm run cref:record). The recorded file lets the Lua
// runner replay C-verified outcomes without a C compiler.
//

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { get2dRange, getApprox2dRange } from "../../src/core/maths/range";
import { toFloat32 } from "../../src/core/float32";
import { runScenario, type ScenarioOutcome } from "../scenarios/campaign-scenario";
import { C_REFERENCE_RANDOM_CASES } from "../scenarios/generated/c-reference-random.cases";
import { C_REFERENCE_RANDOM_TIMELINES } from "../scenarios/generated/c-reference-random-timelines.cases";
import { runTimeline, type TimelineOutcome } from "../scenarios/update-timeline";
import { C_REFERENCE_RANDOM_LIFECYCLES } from "../scenarios/generated/c-reference-random-lifecycles.cases";
import { runLifecycle } from "../scenarios/lifecycle-scenario";
import { runCLifecycle, runCRange, runCScenario, runCTimeline } from "./c-harness";
import {
	generateRandomForceLowOnSupplies,
	generateRandomKeysiteCargo,
	generateRandomLifecycles,
	generateRandomScenarios,
	generateRandomSupplyTaskTransaction,
	generateValidRandomSupplyTaskAssignment,
	generateRandomSupplyTaskConstruction,
	generateRandomTimelines,
	mulberry32,
} from "./random-scenarios";
import { C_REFERENCE_RANDOM_KEYSITE_CARGO } from "../scenarios/generated/c-reference-random-keysite-cargo.cases";
import { C_REFERENCE_RANDOM_FORCE_LOW_ON_SUPPLIES } from "../scenarios/generated/c-reference-random-force-low-on-supplies.cases";
import { C_REFERENCE_RANDOM_SUPPLY_TASK_CONSTRUCTION } from "../scenarios/generated/c-reference-random-supply-task-construction.cases";
import { C_REFERENCE_RANDOM_SUPPLY_TASK_ASSIGNMENT } from "../scenarios/generated/c-reference-random-supply-task-assignment.cases";
import { C_REFERENCE_MIGRATED_SUPPLY_TASK_TRANSACTION } from "../scenarios/generated/c-reference-migrated-supply-task-transaction.cases";
import { C_REFERENCE_RANDOM_SUPPLY_TASK_TRANSACTION } from "../scenarios/generated/c-reference-random-supply-task-transaction.cases";

const RECORDED_SEED = 20260922;
const RECORDED_COUNT = 250;

const RECORDED_TIMELINE_SEED = 20260923;
const RECORDED_TIMELINE_COUNT = 150;

const RECORDED_LIFECYCLE_SEED = 20260924;
const RECORDED_LIFECYCLE_COUNT = 150;

const RECORDED_KEYSITE_CARGO_SEED = 20261011;
const RECORDED_KEYSITE_CARGO_COUNT = 150;

const RECORDED_FORCE_LOW_ON_SUPPLIES_SEED = 20261013;
const RECORDED_FORCE_LOW_ON_SUPPLIES_COUNT = 150;

const RECORDED_SUPPLY_TASK_CONSTRUCTION_SEED = 20261014;
const RECORDED_SUPPLY_TASK_CONSTRUCTION_COUNT = 150;

const RECORDED_SUPPLY_TASK_ASSIGNMENT_COUNT = 150;
const RECORDED_SUPPLY_TASK_TRANSACTION_SEED = 20261023;
const RECORDED_SUPPLY_TASK_TRANSACTION_COUNT = 150;

function assertNoNegativeZero(value: unknown, path: string): void {
	if (typeof value === "number" && Object.is(value, -0)) {
		throw new Error(`${path} is -0, which the recorded fixture cannot represent`);
	}
	if (typeof value === "object" && value !== null) {
		for (const [k, v] of Object.entries(value)) {
			assertNoNegativeZero(v, `${path}.${k}`);
		}
	}
}

describe("C reference: recorded random scenarios", () => {
	if (process.env.RECORD_CREF === "1") {
		it("records the fixture from the original C", () => {
			const cases = generateRandomScenarios(RECORDED_SEED, RECORDED_COUNT).map((spec, i) => {
				const expected: ScenarioOutcome = runCScenario(spec);
				assertNoNegativeZero(expected, `case ${i}`);
				return { id: `random-${RECORDED_SEED}-${i}`, c: "random scenario, outcome recorded from the original C", spec, expected };
			});
			const text = [
				"//",
				"// GENERATED by `npm run cref:record` from the executed original EECH C",
				`// (c-reference/harness.c, seed ${RECORDED_SEED}). Do not edit.`,
				"//",
				"",
				'import type { ConformanceCase } from "../assess-group-supplies.cases";',
				"",
				`export const C_REFERENCE_RANDOM_CASES: ConformanceCase[] = ${JSON.stringify(cases, null, "\t")};`,
				"",
			].join("\n");
			writeFileSync(join(__dirname, "../scenarios/generated/c-reference-random.cases.ts"), text);
		});
		it("records the timeline fixture from the original C", () => {
			const cases = generateRandomTimelines(RECORDED_TIMELINE_SEED, RECORDED_TIMELINE_COUNT).map((spec, i) => {
				const expected: TimelineOutcome = runCTimeline(spec);
				assertNoNegativeZero(expected, `timeline ${i}`);
				return { id: `timeline-${RECORDED_TIMELINE_SEED}-${i}`, c: "random timeline, outcome recorded from the original C", spec, expected };
			});
			const text = [
				"//",
				"// GENERATED by `npm run cref:record` from the executed original EECH C",
				`// (c-reference/harness.c timeline mode, seed ${RECORDED_TIMELINE_SEED}). Do not edit.`,
				"//",
				"",
				'import type { TimelineCase } from "../update-timeline.cases";',
				"",
				`export const C_REFERENCE_RANDOM_TIMELINES: TimelineCase[] = ${JSON.stringify(cases, null, "\t")};`,
				"",
			].join("\n");
			writeFileSync(join(__dirname, "../scenarios/generated/c-reference-random-timelines.cases.ts"), text);
		});
		it("records the lifecycle fixture from the original C", () => {
			const cases = generateRandomLifecycles(RECORDED_LIFECYCLE_SEED, RECORDED_LIFECYCLE_COUNT).map((spec, i) => ({
				id: `lifecycle-${RECORDED_LIFECYCLE_SEED}-${i}`,
				c: "random lifecycle, output recorded from the original C",
				spec,
				expected: runCLifecycle(spec),
			}));
			const text = [
				"//",
				"// GENERATED by `npm run cref:record` from the executed original EECH C",
				`// (c-reference/harness.c lifecycle mode, seed ${RECORDED_LIFECYCLE_SEED}). Do not edit.`,
				"// `expected` is the harness's whole output.",
				"//",
				"",
				'import type { LifecycleCase } from "../entity-lifecycle.cases";',
				"",
				`export const C_REFERENCE_RANDOM_LIFECYCLES: LifecycleCase[] = ${JSON.stringify(cases, null, "\t")};`,
				"",
			].join("\n");
			writeFileSync(join(__dirname, "../scenarios/generated/c-reference-random-lifecycles.cases.ts"), text);
		});

		it("records the keysite cargo fixture from the original C", () => {
			const cases = generateRandomKeysiteCargo(RECORDED_KEYSITE_CARGO_SEED, RECORDED_KEYSITE_CARGO_COUNT).map((spec, i) => ({
				id: `keysite-cargo-${RECORDED_KEYSITE_CARGO_SEED}-${i}`,
				c: "random keysite cargo scenario, output recorded from the original C",
				spec,
				expected: runCLifecycle(spec),
			}));
			const text = [
				"//",
				"// GENERATED by `npm run cref:record` from the executed original EECH C",
				`// (c-reference/harness.c, keysite.c :: update_keysite_cargo, seed ${RECORDED_KEYSITE_CARGO_SEED}). Do not edit.`,
				"// `expected` is the harness's whole output.",
				"//",
				"",
				'import type { LifecycleCase } from "../entity-lifecycle.cases";',
				"",
				`export const C_REFERENCE_RANDOM_KEYSITE_CARGO: LifecycleCase[] = ${JSON.stringify(cases, null, "\t")};`,
				"",
			].join("\n");
			writeFileSync(join(__dirname, "../scenarios/generated/c-reference-random-keysite-cargo.cases.ts"), text);
		});

		it("records the force low-on-supplies fixture from the original C", () => {
			const cases = generateRandomForceLowOnSupplies(RECORDED_FORCE_LOW_ON_SUPPLIES_SEED, RECORDED_FORCE_LOW_ON_SUPPLIES_COUNT).map((spec, i) => ({
				id: `force-low-on-supplies-${RECORDED_FORCE_LOW_ON_SUPPLIES_SEED}-${i}`,
				c: "random force low-on-supplies scenario, output recorded from the original C",
				spec,
				expected: runCLifecycle(spec),
			}));
			const text = [
				"//",
				"// GENERATED by `npm run cref:record` from the executed original EECH C",
				`// (c-reference/harness.c, fc_msgs.c :: response_to_force_low_on_supplies, seed ${RECORDED_FORCE_LOW_ON_SUPPLIES_SEED}). Do not edit.`,
				"// `expected` is the harness's whole output.",
				"//",
				"",
				'import type { LifecycleCase } from "../entity-lifecycle.cases";',
				"",
				`export const C_REFERENCE_RANDOM_FORCE_LOW_ON_SUPPLIES: LifecycleCase[] = ${JSON.stringify(cases, null, "\t")};`,
				"",
			].join("\n");
			writeFileSync(join(__dirname, "../scenarios/generated/c-reference-random-force-low-on-supplies.cases.ts"), text);
		});

		it("records the supply task construction fixture from the original C", () => {
			const cases = generateRandomSupplyTaskConstruction(RECORDED_SUPPLY_TASK_CONSTRUCTION_SEED, RECORDED_SUPPLY_TASK_CONSTRUCTION_COUNT).map((spec, i) => ({
				id: `supply-task-construction-${RECORDED_SUPPLY_TASK_CONSTRUCTION_SEED}-${i}`,
				c: "random supply task construction scenario, output recorded from the original C",
				spec,
				expected: runCLifecycle(spec),
			}));
			const text = [
				"//",
				"// GENERATED by `npm run cref:record` from the executed original EECH C",
				`// (c-reference/harness.c, taskgen.c :: create_supply_task -> create_task, seed ${RECORDED_SUPPLY_TASK_CONSTRUCTION_SEED}). Do not edit.`,
				"// `expected` is the harness's whole output.",
				"//",
				"",
				'import type { LifecycleCase } from "../entity-lifecycle.cases";',
				"",
				`export const C_REFERENCE_RANDOM_SUPPLY_TASK_CONSTRUCTION: LifecycleCase[] = ${JSON.stringify(cases, null, "\t")};`,
				"",
			].join("\n");
			writeFileSync(join(__dirname, "../scenarios/generated/c-reference-random-supply-task-construction.cases.ts"), text);
		});

		// the supply task assignment fixtures (Slice 6a's scenarios migrated to 6b's state invariants)
		// are recorded by test/c-reference/slice-6a-migration.cref.test.ts

		it("records the supply task transaction fixture from the original C", () => {
			const cases = generateRandomSupplyTaskTransaction(RECORDED_SUPPLY_TASK_TRANSACTION_SEED, RECORDED_SUPPLY_TASK_TRANSACTION_COUNT).map((spec, i) => ({
				id: `supply-task-transaction-${RECORDED_SUPPLY_TASK_TRANSACTION_SEED}-${i}`,
				c: "random supply task transaction scenario, output recorded from the original C",
				spec,
				expected: runCLifecycle(spec),
			}));
			const text = [
				"//",
				"// GENERATED by `npm run cref:record` from the executed original EECH C",
				`// (c-reference/harness.c, assign.c's transaction to assign_task_to_group_members, seed ${RECORDED_SUPPLY_TASK_TRANSACTION_SEED}). Do not edit.`,
				"// `expected` is the harness's whole output.",
				"//",
				"",
				'import type { LifecycleCase } from "../entity-lifecycle.cases";',
				"",
				`export const C_REFERENCE_RANDOM_SUPPLY_TASK_TRANSACTION: LifecycleCase[] = ${JSON.stringify(cases, null, "\t")};`,
				"",
			].join("\n");
			writeFileSync(join(__dirname, "../scenarios/generated/c-reference-random-supply-task-transaction.cases.ts"), text);
		});
		return;
	}

	it("the fixture is non-trivial", () => {
		expect(C_REFERENCE_RANDOM_CASES.length).toBe(RECORDED_COUNT);
	});

	it("every recorded outcome is still what the original C produces", () => {
		for (const c of C_REFERENCE_RANDOM_CASES) {
			expect(runCScenario(c.spec), c.id).toEqual(c.expected);
		}
	});

	it("the timeline fixture is non-trivial", () => {
		expect(C_REFERENCE_RANDOM_TIMELINES.length).toBe(RECORDED_TIMELINE_COUNT);
	});

	it("every recorded timeline is still what the original C produces", () => {
		for (const c of C_REFERENCE_RANDOM_TIMELINES) {
			expect(runCTimeline(c.spec), c.id).toEqual(c.expected);
		}
	});

	it("the lifecycle fixture is non-trivial", () => {
		expect(C_REFERENCE_RANDOM_LIFECYCLES.length).toBe(RECORDED_LIFECYCLE_COUNT);
	});

	it("every recorded lifecycle is still what the original C produces", () => {
		for (const c of C_REFERENCE_RANDOM_LIFECYCLES) {
			expect(runCLifecycle(c.spec), c.id).toEqual(c.expected);
		}
	});

	it("the keysite cargo fixture is non-trivial", () => {
		expect(C_REFERENCE_RANDOM_KEYSITE_CARGO.length).toBe(RECORDED_KEYSITE_CARGO_COUNT);
	});

	it("every recorded keysite cargo scenario is still what the original C produces", () => {
		for (const c of C_REFERENCE_RANDOM_KEYSITE_CARGO) {
			expect(runCLifecycle(c.spec), c.id).toEqual(c.expected);
		}
	});

	it("the force low-on-supplies fixture is non-trivial", () => {
		expect(C_REFERENCE_RANDOM_FORCE_LOW_ON_SUPPLIES.length).toBe(RECORDED_FORCE_LOW_ON_SUPPLIES_COUNT);
	});

	it("every recorded force low-on-supplies scenario is still what the original C produces", () => {
		for (const c of C_REFERENCE_RANDOM_FORCE_LOW_ON_SUPPLIES) {
			expect(runCLifecycle(c.spec), c.id).toEqual(c.expected);
		}
	});

	it("the supply task construction fixture is non-trivial", () => {
		expect(C_REFERENCE_RANDOM_SUPPLY_TASK_CONSTRUCTION.length).toBe(RECORDED_SUPPLY_TASK_CONSTRUCTION_COUNT);
		expect(C_REFERENCE_RANDOM_SUPPLY_TASK_CONSTRUCTION.filter((c) => c.expected.some((line) => line.startsWith("transmit-switch-parent "))).length).toBeGreaterThan(10);
	});

	it("every recorded supply task construction scenario is still what the original C produces", () => {
		for (const c of C_REFERENCE_RANDOM_SUPPLY_TASK_CONSTRUCTION) {
			expect(runCLifecycle(c.spec), c.id).toEqual(c.expected);
		}
	});

	it("the migrated supply task assignment fixtures together hold Slice 6a's whole recorded corpus", () => {
		expect(C_REFERENCE_RANDOM_SUPPLY_TASK_ASSIGNMENT.length + C_REFERENCE_MIGRATED_SUPPLY_TASK_TRANSACTION.length).toBe(RECORDED_SUPPLY_TASK_ASSIGNMENT_COUNT);
		// the selection corpus keeps decisions of task types other than SUPPLY at the 6a boundary
		expect(C_REFERENCE_RANDOM_SUPPLY_TASK_ASSIGNMENT.filter((c) => c.expected.some((line) => line.startsWith("result boundary assign_primary_task_to_group "))).length).toBeGreaterThan(3);
		expect(C_REFERENCE_MIGRATED_SUPPLY_TASK_TRANSACTION.every((c) => c.expected.some((line) => line.startsWith("result boundary assign_task_to_group_members ")))).toBe(true);
	});

	it("the supply task transaction fixture is non-trivial", () => {
		expect(C_REFERENCE_RANDOM_SUPPLY_TASK_TRANSACTION.length).toBe(RECORDED_SUPPLY_TASK_TRANSACTION_COUNT);
		expect(C_REFERENCE_RANDOM_SUPPLY_TASK_TRANSACTION.filter((c) => c.expected.some((line) => line.startsWith("result boundary assign_task_to_group_members "))).length).toBeGreaterThan(80);
	});

	it("every recorded supply task transaction scenario is still what the original C produces", () => {
		for (const c of C_REFERENCE_RANDOM_SUPPLY_TASK_TRANSACTION) {
			expect(runCLifecycle(c.spec), c.id).toEqual(c.expected);
		}
	});

	it("every recorded supply task assignment scenario is still what the original C produces", () => {
		for (const c of [...C_REFERENCE_RANDOM_SUPPLY_TASK_ASSIGNMENT, ...C_REFERENCE_MIGRATED_SUPPLY_TASK_TRANSACTION]) {
			expect(runCLifecycle(c.spec), c.id).toEqual(c.expected);
		}
	});
});

describe("C reference: live differential", () => {
	it("TypeScript matches the original C on 1500 fresh random scenarios", () => {
		const branches: Record<string, number> = {};
		for (const spec of generateRandomScenarios(0xeec4, 1500)) {
			const c = runCScenario(spec);
			expect(runScenario(spec)).toEqual(c);
			const key = `${spec.op.kind}:${c.result}:${c.transmissions.length}:${c.messages.length}`;
			branches[key] = (branches[key] ?? 0) + 1;
		}
		// the generator must keep reaching the interesting outcomes
		const kinds = Object.keys(branches).join(" ");
		expect(kinds).toContain("assess:ok:4:0");
		expect(kinds).toContain("assess:ok:0:1");
		expect(kinds).toContain("assess:assert:receiver");
		expect(kinds).toContain("assess:assert:keysite");
		expect(kinds).toContain("assess:null-dereference");
		expect(kinds).toContain("closest:ok");
		expect(kinds).toContain("closest:assert:v2");
	});

	it("TypeScript matches the original C on 1000 fresh random update timelines", () => {
		const reached: Record<string, boolean> = {};
		for (const spec of generateRandomTimelines(0x7153, 1000)) {
			const c = runCTimeline(spec);
			expect(runTimeline(spec)).toEqual(c);
			reached[c.result] = true;
			for (let i = 0; i < c.steps.length; i++) {
				const before = i === 0 ? undefined : c.steps[i - 1];
				const step = spec.steps[i];
				if (step.kind === "frame" && step.count > 0 && before !== undefined && before.updateList.length > c.steps[i].updateList.length) {
					reached["expiry"] = true;
				}
				if (step.kind === "frame" && step.count > 0 && !step.locked && step.delta * spec.entityUpdateFrameRate + 1 >= 3) {
					reached["subdivided"] = true;
				}
				if (step.kind === "frame" && step.locked) {
					reached["locked"] = true;
				}
			}
		}
		// the generator must keep reaching the interesting outcomes
		for (const key of ["ok", "assert:(frame_rate >= 1) && (frame_rate <= 100)", "expiry", "subdivided", "locked"]) {
			expect(reached[key], key).toBe(true);
		}
	});

	it("TypeScript matches the original C on 1000 fresh random entity lifecycles", () => {
		const reached: Record<string, boolean> = {};
		for (const spec of generateRandomLifecycles(0x11fe, 1000)) {
			const c = runCLifecycle(spec);
			expect(runLifecycle(spec)).toEqual(c);
			for (const line of c) {
				if (line.startsWith("result ")) {
					reached[line] = true;
				}
				if (line.startsWith("transmit-destroy")) {
					reached["destroy"] = true;
				}
				if (line.startsWith("allocated ")) {
					reached["allocated"] = true;
				}
			}
			if (c.some((line) => line.startsWith("created ")) && c.some((line) => /^keysite \S+ \S+ \S+/.test(line))) {
				reached["two crates in one keysite"] = true;
			}
		}
		// the generator must keep reaching the interesting outcomes
		for (const key of [
			"result ok",
			"destroy",
			"allocated",
			"result fatal Entity already in use: %s (index = %d)",
			"result assert (index >= 0) && (index < number_of_entities)",
			"two crates in one keysite",
			"result fatal Position off map: (x = %f, z = %f)",
			"result fatal EN_CREATE: CREATE_CLIENT_SERVER_ENTITY : unable to create entity %s. Limit of %d reached",
			"result fatal EN_CREATE: CREATE_LOCAL_ENTITY : unable to create entity %s. Limit of %d reached",
			"result fatal SC_CREAT: uninitialised sector entity",
			"result assert assert_local_create_entity_index ((index))",
			"result assert (type > ENTITY_TYPE_UNKNOWN) && (type < NUM_ENTITY_TYPES)",
			"result assert int_bit_count (sector_side_length) == 1",
			"result assert num_map_x_sectors > 0",
		]) {
			expect(reached[key], key).toBe(true);
		}
	});

	it("TypeScript matches the original C on 1000 fresh random keysite cargo scenarios", () => {
		const reached: Record<string, boolean> = {};
		for (const spec of generateRandomKeysiteCargo(0x4ca6, 1000)) {
			const c = runCLifecycle(spec);
			expect(runLifecycle(spec)).toEqual(c);
			for (const line of c) {
				if (line.startsWith("result ")) {
					reached[line] = true;
				}
				for (const prefix of ["transmit-create", "transmit-destroy", "message"]) {
					if (line.startsWith(prefix)) {
						reached[prefix] = true;
					}
				}
			}
			// a crate created and the level still at or below the threshold: no message for that call
			if (c.some((line) => line.startsWith("transmit-create")) && c.some((line) => line.startsWith("message"))) {
				reached["create and notify in one scenario"] = true;
			}
		}
		// the generator must keep reaching the interesting outcomes
		for (const key of [
			"result ok",
			"transmit-create",
			"transmit-destroy",
			"message",
			"create and notify in one scenario",
			"result assert receiver",
			"result fatal EN_CREATE: CREATE_CLIENT_SERVER_ENTITY : unable to create entity %s. Limit of %d reached",
		]) {
			expect(reached[key], key).toBe(true);
		}
	});

	it("TypeScript matches the original C on 1000 fresh random force low-on-supplies scenarios", () => {
		const reached: Record<string, boolean> = {};
		for (const spec of generateRandomForceLowOnSupplies(0x5a12, 1000)) {
			const c = runCLifecycle(spec);
			expect(runLifecycle(spec)).toEqual(c);
			for (const line of c) {
				if (line.startsWith("result ")) {
					reached[line] = true;
				}
				const words = line.split(" ");
				if (words[0] === "create-supply-task") {
					reached[words[1] === words[2] ? "an airbase supplies itself" : words[1].startsWith("g") ? "a group is supplied" : "another keysite supplies"] = true;
				}
				if (words[0] === "message") {
					reached[words[2].startsWith("g") ? "a group requests" : "a keysite requests"] = true;
				}
			}
			const messages = c.filter((line) => line.startsWith("message ")).length;
			const calls = c.filter((line) => line.startsWith("create-supply-task ")).length;
			if (messages > calls) {
				reached["a request without a call"] = true;
			}
		}
		// the generator must keep reaching the interesting outcomes
		for (const key of [
			"result ok",
			"result assert v2",
			"result assert receiver",
			"an airbase supplies itself",
			"another keysite supplies",
			"a group is supplied",
			"a keysite requests",
			"a group requests",
			"a request without a call",
		]) {
			expect(reached[key], key).toBe(true);
		}
	});

	it("TypeScript matches the original C on 1000 fresh random supply task construction scenarios", () => {
		const reached: Record<string, boolean> = {};
		for (const spec of generateRandomSupplyTaskConstruction(0x5b14, 1000)) {
			const c = runCLifecycle(spec);
			expect(runLifecycle(spec)).toEqual(c);
			const calls = c.filter((line) => line.startsWith("create-supply-task ")).length;
			const created = c.filter((line) => line.startsWith("transmit-switch-parent ") || line.startsWith("campaign mission-created ")).length;
			for (const line of c) {
				const words = line.split(" ");
				if (line.startsWith("result ")) {
					reached[line] = true;
				}
				if (words[0] === "task" && words[17] === "difficulty") {
					reached[Number(words[18]) > 0 ? "a task with a difficulty" : "a task without difficulty"] = true;
					reached[Number(words[10]) >= 4094 ? "a task id at the wrap" : "a task id"] = true;
				}
				if (words[0] === "unassigned" && words.length > 3) {
					reached["two unassigned tasks at a keysite"] = true;
				}
				if (words[0] === "force" && words[3] !== "0" && !c.some((l) => l.startsWith("transmit-"))) {
					reached["a single player task"] = true;
				}
			}
			if (calls > 0 && created === 0 && !c.some((l) => l.startsWith("route "))) {
				reached["a call without a task"] = true;
			}
		}
		// the generator must keep reaching the interesting outcomes
		for (const key of [
			"result ok",
			"result assert point_inside_map_volume (v) || v->y == -10000",
			"a task with a difficulty",
			"a task without difficulty",
			"a task id",
			"a task id at the wrap",
			"two unassigned tasks at a keysite",
			"a single player task",
			"a call without a task",
		]) {
			expect(reached[key], key).toBe(true);
		}
	});

	it("TypeScript matches the original C on 1000 fresh random supply task assignment scenarios", () => {
		const reached: Record<string, number> = {};
		const count = (key: string): void => {
			reached[key] = (reached[key] ?? 0) + 1;
		};
		for (const spec of generateValidRandomSupplyTaskAssignment(0x6a16, 1000)) {
			const c = runCLifecycle(spec);
			expect(runLifecycle(spec)).toEqual(c);
			for (const line of c) {
				if (line.startsWith("result boundary assign_primary_task_to_group ")) {
					count("a task other than SUPPLY is selected (the 6a decision boundary)");
				} else if (line.startsWith("result boundary assign_task_to_group_members ")) {
					count("a SUPPLY task is assigned (the 6b boundary)");
				} else if (line.startsWith("transmit-int task")) {
					count("a constructed task is assigned");
				} else if (line.startsWith("result ")) {
					count(line);
				}
			}
		}
		// the generator must keep reaching the interesting outcomes
		for (const key of [
			"result ok",
			"a task other than SUPPLY is selected (the 6a decision boundary)",
			"a SUPPLY task is assigned (the 6b boundary)",
			"a constructed task is assigned",
			"result assert force",
			"result assert objective",
			"result assert get_comms_model () == COMMS_MODEL_SERVER",
		]) {
			expect(reached[key] ?? 0, `${key} ${JSON.stringify(reached)}`).toBeGreaterThan(0);
		}
	});

	it("TypeScript matches the original C on 1000 fresh random supply task transaction scenarios", () => {
		const reached: Record<string, number> = {};
		const count = (key: string): void => {
			reached[key] = (reached[key] ?? 0) + 1;
		};
		for (const spec of generateRandomSupplyTaskTransaction(0x6b18, 1000)) {
			const c = runCLifecycle(spec);
			expect(runLifecycle(spec)).toEqual(c);
			const waypoints = c.filter((line) => line.startsWith("waypoint ")).length;
			for (const line of c) {
				if (line.startsWith("result ")) {
					count(line.startsWith("result boundary assign_task_to_group_members ") ? "the 6b boundary" : line);
				} else if (line.startsWith("transmit-int task")) {
					count("a constructed task is assigned");
				} else if (line.startsWith("campaign mission-assigned")) {
					count("MISSION_ASSIGNED");
				}
			}
			if (waypoints > 6) {
				count("the route search adds waypoints");
			}
			if (c.some((line) => line.startsWith("terrain "))) {
				count("terrain lookups observed");
			}
		}
		for (const key of ["result ok", "the 6b boundary", "result assert road_node_positions", "a constructed task is assigned", "MISSION_ASSIGNED", "the route search adds waypoints", "terrain lookups observed"]) {
			expect(reached[key] ?? 0, `${key} ${JSON.stringify(reached)}`).toBeGreaterThan(0);
		}
	});

	it("get_2d_range and get_approx_2d_range match the original C bit for bit", () => {
		const rnd = mulberry32(42);
		for (let i = 0; i < 400; i++) {
			const v = [0, 0, 0, 0].map(() => (rnd() - 0.5) * 10 ** Math.floor(rnd() * 7));
			const c = runCRange(v[0], v[1], v[2], v[3]);
			const a = { x: toFloat32(v[0]), y: 0, z: toFloat32(v[1]) };
			const b = { x: toFloat32(v[2]), y: 0, z: toFloat32(v[3]) };
			expect(get2dRange(a, b)).toBe(c.range);
			expect(getApprox2dRange(a, b)).toBe(c.approx);
		}
	});
});
