//
// The round-toward-zero float helpers (src/core/float32.ts) against the C
// float arithmetic of the canonical oracle, bit for bit (signed zeros
// included).
//
// Set RECORD_CREF=1 to rewrite test/scenarios/generated/c-reference-float32-rtz.cases.ts,
// which the vitest suite and the Lua 5.1 runner replay without a C compiler.
//

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { applyFloat32RtzOp, type Float32RtzCase, type Float32RtzOp } from "../scenarios/float32-rtz";
import { float32Hex } from "../scenarios/float-bits";
import { C_REFERENCE_FLOAT32_RTZ_CASES } from "../scenarios/generated/c-reference-float32-rtz.cases";
import { C_REFERENCE_DOUBLE_SUM_RTZ_CASES } from "../scenarios/generated/c-reference-double-sum-rtz.cases";
import { doubleFromBits, floatFromBits, runCFloat32 } from "./c-harness";
import { generateDoubleSumOperands, generateFloat32RtzOperands } from "./random-scenarios";

const RECORDED_SEED = 20260925;
const RECORDED_COUNT = 3000;

// Slice 4 (#10): f64AddRTZ, recorded separately so the #7 fixture stays frozen
const DOUBLE_SUM_SEED = 20261010;
const DOUBLE_SUM_COUNT = 1000;

function literal(n: number): string {
	if (Object.is(n, -0)) return "NEGATIVE_ZERO";
	if (n === 1 / 0) return "1 / 0";
	if (n === -1 / 0) return "-1 / 0";
	return String(n);
}

function float64Hex(value: number): string {
	const view = new DataView(new ArrayBuffer(8));
	view.setFloat64(0, value);
	return view.getUint32(0).toString(16).padStart(8, "0") + view.getUint32(4).toString(16).padStart(8, "0");
}

// the C result as a number: dsum gives double bits, the others float bits
function fromBits(op: Float32RtzOp, hex: string): number {
	return op === "dsum" ? doubleFromBits(hex) : floatFromBits(hex);
}

function compare(ops: [Float32RtzOp, number, number][]): string[] {
	const expected = runCFloat32(ops);
	expect(expected.length).toBe(ops.length);
	const failures: string[] = [];
	ops.forEach(([op, a, b], i) => {
		const value = applyFloat32RtzOp(op, a, b);
		const actual = op === "dsum" ? float64Hex(value) : float32Hex(value);
		// NaN payloads are not modelled (x86 produces the negative default NaN)
		const nan = Number.isNaN(fromBits(op, expected[i]));
		if (nan ? !Number.isNaN(value) : actual !== expected[i]) {
			failures.push(`${op} ${a} ${b}: C ${expected[i]}, TS ${actual}`);
		}
	});
	return failures;
}

describe("C reference: round-toward-zero float arithmetic", () => {
	if (process.env.RECORD_CREF === "1") {
		it("records the fixture from the original C environment", () => {
			// operands and results that the fixture format can carry: no NaN, no -0 operand
			const ops = generateFloat32RtzOperands(RECORDED_SEED, RECORDED_COUNT * 2)
				.filter(([, a, b]) => !Object.is(a, -0) && !Object.is(b, -0))
				.slice(0, RECORDED_COUNT * 2);
			const bits = runCFloat32(ops);
			const cases: string[] = [];
			ops.forEach(([op, a, b], i) => {
				const value = fromBits(op, bits[i]);
				if (!Number.isNaN(value) && cases.length < RECORDED_COUNT) {
					cases.push(`\t["${op}", ${literal(a)}, ${literal(b)}, ${literal(value)}],`);
				}
			});
			const text = [
				"//",
				"// GENERATED by `npm run cref:record` from the original EECH C float arithmetic",
				`// under the canonical environment (c-reference/harness.c f32, seed ${RECORDED_SEED}). Do not edit.`,
				"//",
				"",
				'import type { Float32RtzCase } from "../float32-rtz";',
				"",
				"const NEGATIVE_ZERO = 1 / -(1 / 0);",
				"",
				"export const C_REFERENCE_FLOAT32_RTZ_CASES: Float32RtzCase[] = [",
				...cases,
				"];",
				"",
			].join("\n");
			writeFileSync(join(__dirname, "..", "scenarios", "generated", "c-reference-float32-rtz.cases.ts"), text);
		});

		it("records the double sum fixture from the original C environment", () => {
			const ops = generateDoubleSumOperands(DOUBLE_SUM_SEED, DOUBLE_SUM_COUNT);
			const bits = runCFloat32(ops);
			const cases = ops.map(([op, a, b], i) => `\t["${op}", ${literal(a)}, ${literal(b)}, ${literal(fromBits(op, bits[i]))}],`);
			const text = [
				"//",
				"// GENERATED by `npm run cref:record` from the original EECH C double arithmetic",
				`// under the canonical environment (c-reference/harness.c f32 dsum, seed ${DOUBLE_SUM_SEED}). Do not edit.`,
				"//",
				"",
				'import type { Float32RtzCase } from "../float32-rtz";',
				"",
				"export const C_REFERENCE_DOUBLE_SUM_RTZ_CASES: Float32RtzCase[] = [",
				...cases,
				"];",
				"",
			].join("\n");
			writeFileSync(join(__dirname, "..", "scenarios", "generated", "c-reference-double-sum-rtz.cases.ts"), text);
		});
	}

	it("the fixture is non-trivial", () => {
		expect(C_REFERENCE_FLOAT32_RTZ_CASES.length).toBe(RECORDED_COUNT);
	});

	it("every recorded result is still what the C produces", () => {
		const cases: Float32RtzCase[] = C_REFERENCE_FLOAT32_RTZ_CASES;
		const bits = runCFloat32(cases.map(([op, a, b]) => [op, a, b]));
		cases.forEach(([op, a, b, expected], i) => {
			expect(bits[i], `${op} ${a} ${b}`).toBe(op === "dsum" ? float64Hex(expected) : float32Hex(expected));
		});
	});

	it("the double sum fixture is non-trivial, and still what the C produces", () => {
		const cases: Float32RtzCase[] = C_REFERENCE_DOUBLE_SUM_RTZ_CASES;
		expect(cases.length).toBe(DOUBLE_SUM_COUNT);
		const bits = runCFloat32(cases.map(([op, a, b]) => [op, a, b]));
		cases.forEach(([op, a, b, expected], i) => {
			expect(bits[i], `${op} ${a} ${b}`).toBe(float64Hex(expected));
		});
	});

	it("TypeScript matches C on 20000 fresh double sums", () => {
		const failures = compare(generateDoubleSumOperands(0xd5a4, 20000));
		expect(failures.slice(0, 20)).toEqual([]);
	});

	it("TypeScript matches C on 40000 fresh operations", () => {
		const failures = compare(generateFloat32RtzOperands(0xf32e, 40000));
		expect(failures.slice(0, 20)).toEqual([]);
	});

	it("TypeScript matches C on signed zeros, infinities and boundaries", () => {
		const m = 3.4028234663852886e38;
		const ops: [Float32RtzOp, number, number][] = [
			["narrow", -0, 0],
			["narrow", -1e-50, 0],
			["narrow", 1 / 0, 0],
			["narrow", -1 / 0, 0],
			["narrow", 3.5e38, 0],
			["narrow", -3.5e38, 0],
			["sum", -0, -0],
			["sum", 0, -0],
			["sum", 1, -1],
			["sum", m, m],
			["sum", -m, -m],
			["mul", m, 2],
			["mul", -0, 5],
			["mul", 1e-30, 1e-30],
			["div", 1, 0],
			["div", -1, 0],
			["div", 0, 5],
			["div", -0, 5],
			["div", m, 0.5],
			["sqrt", -0, 0],
			["sqrt", 0, 0],
			["sqrt", 1 / 0, 0],
			["sqrt", 1.401298464324817e-45, 0],
			["dsum", 1, 1.1102230246251567e-16],
			["dsum", 1, 1.1102230246251568e-16],
			["dsum", -1, -1.1102230246251568e-16],
			["dsum", 1.7976931348623157e308, 1.7976931348623157e308],
			["dsum", -1.7976931348623157e308, -1.7976931348623157e308],
			["dsum", 1 / 0, 1],
			["dsum", 2.2250738585072014e-308, -4.9406564584124654e-324],
			["dsum", 4.9406564584124654e-324, -4.9406564584124654e-324],
			["dsum", 1, -1],
			["dsum", 0, -0],
			["dsum", 1048575.9999999999, -8.673617379884035e-19],
			["dsum", 2.350988701644575e-38, -6.223015277861142e-61],
		];
		expect(compare(ops)).toEqual([]);
	});
});
