//
// Slice 4 review (#11): keysite.c's crate-row step
//
//   position.x += (bounding_box->xmax - bounding_box->xmin) + 1.0;
//
// executed as the original expression (harness `f32 crate-row`, float x,
// xmin and xmax, through the stored position.x) against the port's
// decomposition of it (advanceCrateRow: f32Sub, f64AddRTZ, f32Add), bit for
// bit. It pins where the port places the rounding points under the frozen #7
// contract, and is a canary for #9 (x87 intermediate precision).
//
// Set RECORD_CREF=1 to rewrite test/scenarios/generated/c-reference-crate-row.cases.ts,
// which the vitest suite and the Lua 5.1 runner replay without a C compiler.
//

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { advanceCrateRow } from "../../src/entity/special/keysite/keysite";
import { float32Hex } from "../scenarios/float-bits";
import { C_REFERENCE_CRATE_ROW_CASES } from "../scenarios/generated/c-reference-crate-row.cases";
import { floatFromBits, runCCrateRow } from "./c-harness";
import { generateCrateRowOperands } from "./random-scenarios";

const RECORDED_SEED = 20261012;
const RECORDED_COUNT = 1000;

function literal(n: number): string {
	if (Object.is(n, -0)) return "NEGATIVE_ZERO";
	if (n === 1 / 0) return "1 / 0";
	if (n === -1 / 0) return "-1 / 0";
	return String(n);
}

function mismatches(operands: [number, number, number][]): string[] {
	const bits = runCCrateRow(operands);
	expect(bits.length).toBe(operands.length);
	const failures: string[] = [];
	operands.forEach(([x, xmin, xmax], i) => {
		const actual = advanceCrateRow(x, xmin, xmax);
		const nan = Number.isNaN(floatFromBits(bits[i]));
		if (nan ? !Number.isNaN(actual) : float32Hex(actual) !== bits[i]) {
			failures.push(`x ${x} xmin ${xmin} xmax ${xmax}: C ${bits[i]}, TS ${float32Hex(actual)}`);
		}
	});
	return failures;
}

describe("C reference: keysite.c crate-row step", () => {
	if (process.env.RECORD_CREF === "1") {
		it("records the fixture from the original expression", () => {
			const operands = generateCrateRowOperands(RECORDED_SEED, RECORDED_COUNT * 2).filter(([x, a, b]) => !Object.is(x, -0) && !Object.is(a, -0) && !Object.is(b, -0));
			const bits = runCCrateRow(operands);
			const cases: string[] = [];
			operands.forEach(([x, xmin, xmax], i) => {
				const value = floatFromBits(bits[i]);
				if (!Number.isNaN(value) && cases.length < RECORDED_COUNT) {
					cases.push(`\t[${literal(x)}, ${literal(xmin)}, ${literal(xmax)}, ${literal(value)}],`);
				}
			});
			const text = [
				"//",
				"// GENERATED by `npm run cref:record` from the original expression of keysite.c ::",
				"// update_keysite_cargo, position.x += (bounding_box->xmax - bounding_box->xmin) + 1.0,",
				`// under the canonical environment (c-reference/harness.c f32 crate-row, seed ${RECORDED_SEED}). Do not edit.`,
				"// [x, xmin, xmax, stored x]",
				"//",
				"",
				// only when a case needs it (an unused constant fails the Lua build)
				...(cases.some((c) => c.includes("NEGATIVE_ZERO")) ? ["const NEGATIVE_ZERO = 1 / -(1 / 0);", ""] : []),
				"export const C_REFERENCE_CRATE_ROW_CASES: [number, number, number, number][] = [",
				...cases,
				"];",
				"",
			].join("\n");
			writeFileSync(join(__dirname, "..", "scenarios", "generated", "c-reference-crate-row.cases.ts"), text);
		});
	}

	it("the fixture is non-trivial, and still what the C produces", () => {
		expect(C_REFERENCE_CRATE_ROW_CASES.length).toBe(RECORDED_COUNT);
		const bits = runCCrateRow(C_REFERENCE_CRATE_ROW_CASES.map(([x, a, b]) => [x, a, b]));
		C_REFERENCE_CRATE_ROW_CASES.forEach(([x, xmin, xmax, expected], i) => {
			expect(bits[i], `x ${x} xmin ${xmin} xmax ${xmax}`).toBe(float32Hex(expected));
		});
	});

	it("the port's decomposition matches the original expression on 40000 fresh operands", () => {
		expect(mismatches(generateCrateRowOperands(0xc4a7e, 40000)).slice(0, 20)).toEqual([]);
	});

	it("the port's decomposition matches the original expression at its rounding points", () => {
		const f = Math.fround;
		expect(
			mismatches([
				// realistic crates
				[100, -1, 1],
				[f(0.1), f(-0.025), f(0.025)],
				[f(60000.5), f(-1.25), f(1.3)],
				// + 1.0 inexact in double: width below 2^-29, and at least 2^53
				[1, 0, 1e-30],
				[f(3.5), f(1e-20), f(2e-20)],
				[0, f(-Math.pow(2, 60)), f(Math.pow(2, 60))],
				// the float difference overflows to FLT_MAX toward zero
				[0, f(-3e38), f(3e38)],
				// cancellation, zero and negative widths
				[5, f(1.0000001), f(1.0000002)],
				[5, 2, 2],
				[5, 3, 1],
				[5, 3, -1e-30],
				// x large: the stored sum truncates
				[f(16777217), -1, 1],
				[f(1e30), -1, 1],
				[-100, -1, 1],
				// subnormal widths
				[0, 0, 1.401298464324817e-45],
			]),
		).toEqual([]);
	});
});
