[workspace]
resolver = "2"
members = ["crates/eech-sys", "crates/eech-campaign", "crates/eech-harness", "crates/eech-dc", "crates/eech-world"]

[workspace.package]
edition = "2021"
license-file = "../LICENCE"
publish = false
rust-version = "1.80"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
